import { action } from "./_generated/server";
import { ConvexCredentials } from "@convex-dev/auth/providers/ConvexCredentials";
import { convexAuth } from "@convex-dev/auth/server";
import { createAccount, retrieveAccount } from "@convex-dev/auth/server";
import type { DataModel } from "./_generated/dataModel";

export const testAuth = action({
  args: {},
  handler: async (ctx) => {
    const results: string[] = [];
    
    try {
      // Check if JWKS env var exists (auto-generated by convexAuth)
      results.push("JWKS: " + (process.env.JWKS ? "SET" : "NOT SET"));
      results.push("SITE_URL: " + (process.env.SITE_URL || "NOT SET"));
      
      // Check what the auth module exports
      const authMod = await import("@convex-dev/auth/server");
      results.push("Auth server exports: " + Object.keys(authMod).join(", "));
      
    } catch (e: any) {
      results.push("ERROR: " + e.message);
      results.push("Stack: " + (e.stack || "").slice(0, 1000));
    }
    
    return results;
  },
});
