// @generated - This file is automatically generated by Convex codegen.
/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
} from "convex/server";
