name: Deploy Convex Backend
on:
  workflow_dispatch:
  push:
    paths:
      - 'convex/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Set Convex environment variables
        run: |
          npx convex env set SITE_URL "https://give-a-gallon.vercel.app"
          npx convex env set JWT_PRIVATE_KEY "$JWT_KEY"
          npx convex env list
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
          JWT_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      - run: npx convex deploy -y
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
